generator-settings={"biome":"minecraft:the_void","features":true,"lakes":0,"layers":[{"block":"minecraft:air","height":1}],"structure_overrides":[]}
level-name=world
level-type=flat
enable-rcon=true
rcon.password=dslt-neoforge-26.1